### ISSUE TITLE
new version HA 2022.12.1 no funciona

### ISSUE THREAD

**Issue by webtense** [dbrand666/docker-heyu-mqtt#1]
si actualizar a la versión 2022.12.1 de home asisstant deja de funcionar, podrías echarle un vistazo que esta pasando?

**Comment by dbrand666** [comment]
Can you tell me a bit more? I'm on 2022.12.6 and it's working fine here.

**Comment by dbrand666** [comment]
@webtense I'm going to close this for now. Let me know if you need any additional assistance.
